#!/bin/bash
#SBATCH --job-name=BLASTrun
#SBATCH --ntasks=8
#SBATCH --mem=16000


# Align 0, 6, and 24 hour data generated by DNA_Link
export FASTQDIR=/home/abf/Melinda_Duncan_DNALink/Duncan20180919
export OUTDIR=/work/abf/LEC_Time_Series/DNA_Link_Alignment_NoTrim
for i in $(ls $FASTQDIR | grep R1_001.fastq.gz)
do
    echo $i
    j=$(echo $i | sed 's/_L002_R1_001\.fastq\.gz//')
    F="$OUTDIR/$j"_sorted_alignment.bam
    if [ ! -f $F ]; then
	echo sbatch hisat2_paired_slurm.sh "$i" $(echo $i | sed 's/R1_001\.fastq\.gz/R2_001.fastq.gz/') "$j"
	sbatch hisat2_paired_slurm.sh "$i" $(echo $i | sed 's/R1_001\.fastq\.gz/R2_001.fastq.gz/') "$j"
    fi
done

# Align 0, 24 and 48 hour data generated by DBI
export FASTQDIR=/home/abf/Fibronectin_Analysis
export OUTDIR=/work/abf/LEC_Time_Series/DBI_Alignment_NoTrim
for i in $(ls $FASTQDIR | grep R1_001.fastq.gz)
do
    echo $i
    j=$(echo $i | sed 's/_L001_R1_001\.fastq\.gz//')
    F="$OUTDIR/$j"_sorted_alignment.bam
    if [ ! -f $F ]; then
	echo sbatch hisat2_single_slurm.sh "$i" "$j"
	sbatch hisat2_single_slurm.sh "$i" "$j"
    fi
done
